//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_Projekt_Restaurant_Personalplanung.Datenmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzeraccount
    {
        public int ID_Account { get; set; }
        public string Benutzername { get; set; }
        public string Passwort { get; set; }
        public Nullable<bool> IstAdmin { get; set; }
        public Nullable<int> Angestellter { get; set; }
    
        public virtual Mitarbeiter Mitarbeiter { get; set; }
    }
}
