//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_Projekt_Restaurant_Personalplanung.Datenmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EingeteilterMitarbeiter
    {
        public string name { get; set; }
        public int ID_Wochentag { get; set; }
        public int ID_Schicht { get; set; }
    
        public virtual Schicht Schicht { get; set; }
        public virtual Wochentag Wochentag { get; set; }
    }
}
