//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_Projekt_Restaurant_Personalplanung.Datenmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MitarbeiterDienstplan
    {
        public int ID_MitarbeiterDienstplan { get; set; }
        public Nullable<int> MitarbeiterID { get; set; }
        public Nullable<int> DienstplanID { get; set; }
    
        public virtual Dienstplan Dienstplan { get; set; }
        public virtual Mitarbeiter Mitarbeiter { get; set; }
    }
}
