//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_Projekt_Restaurant_Personalplanung.Datenmodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalplanEntities : DbContext
    {
        public PersonalplanEntities()
            : base("name=PersonalplanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzeraccount> Benutzeraccounts { get; set; }
        public virtual DbSet<Dienstplan> Dienstplaene { get; set; }
        public virtual DbSet<Mitarbeiter> Angestellte { get; set; }
        public virtual DbSet<MitarbeiterSchicht> MitarbeiterSchichten { get; set; }
        public virtual DbSet<Schicht> Schichten { get; set; }
        public virtual DbSet<Wochentag> Wochentage { get; set; }
    }
}
